[project]
name = "meikaku-api"
version = "0.1.0"
description = "FastAPI backend for Meikaku"
authors = [{ name = "Wilson Leung", email = "wilson.leung.2054@hotmail.com"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.1",
    "fastapi[standard]>=0.128.0",
    "psycopg[binary]>=3.3.2",
    "ruff>=0.14.11",
    "sqlalchemy>=2.0.45",
]
