[project]
name = "meikaku-api"
version = "0.1.0"
description = "FastAPI backend for Meikaku"
authors = [{ name = "Wilson Leung", email = "wilson.leung.2054@hotmail.com"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.1",
    "debugpy>=1.8.19",
    "fastapi[standard]>=0.128.0",
    "httpx>=0.28.1",
    "psycopg[binary]>=3.3.2",
    "pwdlib[argon2]>=0.3.0",
    "pyjwt>=2.10.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.11",
    "sqlalchemy>=2.0.45",
    "testcontainers[postgres]>=4.14.0",
]
